[character]
success_symbol = "[[󰄛](green) ❯](mauve)"
error_symbol = "[[󰄛](red) ❯](mauve)"
vimcmd_symbol = "[󰄛 ❮](subtext1)"

[git_branch]
style = "bold mauve"

[directory]
truncation_length = 4
style = "bold lavender"
